### ISSUE TITLE
Installing dependency

### ISSUE THREAD

**Issue by rjsbhatia** [floydhub/floyd-docs#47]
Hi, 

I am trying to install a dependency as described on this page: 
http://docs.floydhub.com/guides/jobs/installing_dependencies/

And i get this error when i try to run git clone
Directory contains too many files to upload. If you have data files in the current directory, please upload them separately using "floyd data" command and remove them from here.
See http://docs.floydhub.com/faqs/job/#i-get-too-many-open-files-error-when-i-run-my-project for more details on how to fix this.

rjs

**Comment by narenst** [comment]
This is not directly related to installing dependencies. If you have too many files in the code directory the cli will decline to upload the code. This is to make sure that the user does not upload any dataset as part of the code (since the code directory will be uploaded every run).

We recommend creating a separate dataset with the data and use it in your project at runtime. More explanation around this can be found here: https://docs.floydhub.com/guides/data/mounting_data/
