### ISSUE TITLE
Anaconda conflict???

### ISSUE THREAD

**Issue by LesGuessing** [floydhub/floyd-docs#52]
This issue is about < I love the idea of Floydhub. Saw one of the founders on a webinar. But it seems to rely on virtualenv and my experience is that virtualenv has problems with the Anaconda Distribution of Python (Which I love.)   Here's the error message I got. Bummer, looks like it's back to AWS for me.

[FloydHub install error message.txt](https://github.com/floydhub/floyd-docs/files/1240998/FloydHub.install.error.message.txt)

**Comment by mckayward** [comment]
Hey @LesGuessing. This week we published `conda` package for floyd-cli :tada: 

Python 2.7, 3.5, and 3.6 are supported on Win32, Win64, Linux32, Linux64, and OSX64.

To install:
```
$ conda config --add channels conda-forge
$ conda install -y -c floydhub floydcli
```

Thanks for the feedback. I know it's been a while since you opened this issue, but we still hope these new packages will make installation and management of the floyd-cli easier for you and other anaconda users!
