### ISSUE TITLE
shutting down a server when not in use

### ISSUE THREAD

**Issue by srivathshanks** [floydhub/floyd-docs#86]
As a paid user I value the time I get to use the GPU. It would be better if there is a feature where I can stop the server when the currently running job is complete and the resources are not in use in case I have to leave when the job is running. 

It would be better if the files are saved in case of jupyter mode and shut down.

**Comment by houqp** [comment]
Hi, thanks for the feedback. We have been trainstorming ideas on how to better support this use-case. Right now, we have a 1 hour and 3 hours idle idle time reminder email setup for jupyter notebook jobs. So hopefully this helps a little bit.

On the other hand, is there any reason you prefer using jupyter mode instead of command mode for long running tasks? Command mode job will automatically shutdown after command exits and you can write code to save the state to output at the end of your command.

**Comment by srivathshanks** [comment]
I am a starter in deep learning, So think jupyter is convenient to use. Now I know the command mode shutdown automatically I can use that. 

Thanks for the update. I think I can close the issue.
