### ISSUE TITLE
Where the hell is the Dashboard!!!!!!!!!

### ISSUE THREAD

**Issue by gentleanimal** [floydhub/floyd-docs#95]
This issue is about <When I use floyd login it does start the browser but instead of taking me to the page where the autho token is it takes me to projects. So I click on everything to find the Dashboard page but no go. PUT A LINK ON EVERY PAGE SO PEOPLE CAN ACCESS THE DASHBOARD!!!!!!!

**Comment by houqp** [comment]
Sorry, this is not expected. It should take you to `https://www.floydhub.com/settings/security` based on https://github.com/floydhub/floyd-cli/blob/master/floyd/cli/auth.py#L18.

Could you let us know what version of the client you are using?

@saiprashanths @whatrocks @narenst thoughts on adding auth token link to the top right drop down? Right now it requires 3 clicks from the user to get to that page.

**Comment by saiprashanths** [comment]
The problem is likely this: if the user isn't logged into the web dashboard, the login modal pops up when trying to access the settings/security page. After logging in, it redirects to the welcome or projects page, which is obviously bad UX. So there's 2 fixes here:
1. Redirect to the correct destination after login
2. Add CLI token to the dropdown

**Comment by houqp** [comment]
Ha, good point, I think that's what caused it. We should definitely fix the login redirect.

**Comment by houqp** [comment]
@gentleanimal we have added the token link to the upper menu dropdown as well as implemented redirect on login. So you won't run into this issue anymore.
